peso = float(input("Qual o seu peso? "))
alt = float(input("Qual a sua Altura? "))
imc = peso / (alt * alt)
print(f"Seu imc e {imc:.2f} ")
print("Tabela de IMC")
print("")
print("Menor que 18.5    --> Abaixo do Peso   ")
print("Entre 18.5 a 24.9 --> Peso Normal      ")
print("Entre 25 a 29.9   --> Sobrepeso        ")
print("Entre 30 a 34.9   --> Obesidade Grau I ")
print("Entre 35 a 39.9   --> Obesidade Grau II")
print("Maior que 40      --> Obesidade Mórbida")  